apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobworker-deployment
  labels:
    app: jobworker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jobworker
  template:
    metadata:
      labels:
        app: jobworker
    spec:
      containers:
      - name: jobworker
        image: gcr.io/unger-api/jobworker:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jobworker-service
spec:
  selector:
    app: jobworker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP