apiVersion: apps/v1
kind: Deployment
metadata:
  name: ungerapi-deployment
  labels:
    app: ungerapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ungerapi
  template:
    metadata:
      labels:
        app: ungerapi
    spec:
      containers:
      - name: ungerapi
        image: gcr.io/unger-api/ungerapi:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ungerapi-service
spec:
  selector:
    app: ungerapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer