name: CI/CD

on:
  push:
    branches:
    - main

jobs:
  setup-build-publish-deply:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./UngerApi.Minimal/
        push: true
        tags: gcr.io/${{ vars.GKE_PROJECT}}/ungerapi:latest

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ vars.GKE_PROJECT }}
    
    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: |-
        gcloud --quiet auth configure-docker

    - name: Install auth plugin
      run: |-
        gcloud components install gke-gcloud-auth-plugin

    - name: Deploy to GKE
      run: |-
        gcloud container clusters get-credentials ${{ vars.GKE_CLUSTER }} --zone ${{ vars.GKE_ZONE }}
        kubectl apply -f ./UngerApi.Minimal/deploy.yml

    